GENRE_CHOICES = [
    ("autre", "Other"),
    ("chill", "Chill"),
    ("classical", "Classical"),
    ("cloud_trap", "Cloud Trap"),
    ("country", "Country"),
    ("dance_edm", "Dance & EDM"),
    ("dancehall", "Dancehall"),
    ("deep_house", "Deep House"),
    ("disco", "Disco"),
    ("drill", "Drill"),
    ("drum_bass", "Drum & Bass"),
    ("dubstep", "Dubstep"),
    ("electro", "Electro"),
    ("folk", "Folk"),
    ("hiphop", "Hip-Hop"),
    ("hood_trap", "Hood Trap"),
    ("house", "House"),
    ("indie", "Indie"),
    ("infected", "Infected"),
    ("jazz_blues", "Jazz & Blues"),
    ("jersey", "Jersey"),
    ("video_game", "Video Game"),
    ("latin", "Latin"),
    ("love_rap", "Love Rap"),
    ("love_trap", "Love Trap"),
    ("metal", "Metal"),
    ("movie_music", "Movie Soundtrack"),
    ("new_wave", "New Wave"),
    ("old_school", "Old School"),
    ("phonk", "Phonk"),
    ("piano", "Piano"),
    ("pop", "Pop"),
    ("rnb_soul", "R&B & Soul"),
    ("rap", "Rap"),
    ("reggae", "Reggae"),
    ("reggaeton", "Reggaeton"),
    ("rock", "Rock"),
    ("alt_rock", "Alternative Rock"),
    ("techno", "Techno"),
    ("trance", "Trance"),
    ("trap", "Trap"),
    ("triphop", "Triphop"),
    ("west_coast", "West Coast"),
    ("world", "World"),
]

KEY_CHOICES = [
    ("Am", "A minor"), ("A", "A major"), ("A#", "A# major"), ("A#m", "A# minor"),
    ("B", "B major"), ("Bm", "B minor"), ("C", "C major"), ("Cm", "C minor"),
    ("C#", "C# major"), ("C#m", "C# minor"), ("D", "D major"), ("Dm", "D minor"),
    ("D#", "D# major"), ("D#m", "D# minor"), ("E", "E major"), ("Em", "E minor"),
    ("F", "F major"), ("Fm", "F minor"), ("F#", "F# major"), ("F#m", "F# minor"),
    ("G", "G major"), ("Gm", "G minor"), ("G#", "G# major"), ("G#m", "G# minor"),
]

STATUS_CHOICES = [
    ("draft", "Draft"),
    ("published", "Published"),
]